const defaultTitles = [
    // Basic 
    "My Bucket List",
    "Best Movies I Watched",
    "Let's Go to Japan",
    "Things I Want to Learn",
    "Ideas Worth Building",
    "Books I Need to Read",
    "Dream Travel Destinations",
    "Weekend Plans",
    "Random Thoughts",
    "Lessons From Today",
    "Things I Should Remember",
    "My Favorite Recipes",
    "Future Business Ideas",
    "Goals for This Year",
    "A Letter to My Future Self",
    "Notes From the Grocery Store",
    "My Fitness Journey",
    "Things That Make Me Happy",
    "Places I Want to Visit",
    "Songs On Repeat",
    "Daily Journal",
    "Late Night Thoughts",
    "Life Lessons",
    "Things I Learned Recently",
    "Project Brainstorm",
    "Startup Ideas",
    "Coding Notes",
    "Books That Changed My Mind",
    "Things I Need to Do",
    "How I Spent My Weekend",
    "My Experience at the Grocery Store",
    "The Perfect Morning Routine",
    "What If I Moved Abroad?",
    "How to Become Better",
    "Memories Worth Keeping",
    "The Next Big Thing",
    "Things I Wish I Knew Earlier",
    "A Day I'll Never Forget",
    "Plans for 2030",
    "If Money Wasn't a Problem",

    // ── Life & Reflection ──────────────────────────────────────
    "A Letter to My Future Self",
    "A Day I'll Never Forget",
    "Memories Worth Keeping",
    "Things I Wish I Knew Earlier",
    "Life Lessons I Keep Learning",
    "Moments That Changed Everything",
    "The Best Advice I Ever Received",
    "Who I Was vs. Who I Am Now",
    "Things I Want to Remember Forever",
    "The Year in Review",
    "What This Chapter of Life Taught Me",
    "Letters I Never Sent",
    "The Story I Never Tell Anyone",
    "What I Would Tell My Younger Self",
    "Things I've Changed My Mind About",
    "The Hardest Decision I Ever Made",
    "A Day I Wish I Could Relive",
    "Things That Shaped Who I Am",
    "Turning Points",
    "What Growing Up Really Means",
    "The Moment Everything Clicked",
    "Things I Am Still Learning",
    "Conversations That Stayed With Me",
    "What Home Means to Me",
    "The People Who Made Me",
    "Chapters I Want to Rewrite",
    "The Version of Myself I'm Working Toward",
    "Things I Took for Granted",
    "What I Know for Certain",
    "What I'm Still Figuring Out",
    "The Small Things That Matter Most",
    "Where I See Myself in Ten Years",
    "What I Want My Life to Look Like",
    "Milestones Worth Celebrating",
    "Everything I Believe In",
    "The Most Important Thing I've Learned",
    "Things I Would Do Differently",
    "Lessons From the Hard Times",
    "How I Got Through It",
    "What Keeps Me Going",

    // ── Goals & Dreams ────────────────────────────────────────
    "Goals for This Year",
    "My Bucket List",
    "Plans for 2030",
    "If Money Wasn't a Problem",
    "Things I Want to Learn",
    "Dreams I Haven't Given Up On",
    "100 Things I Want to Do Before I Die",
    "The Life I'm Building Toward",
    "Five Years from Now",
    "Things I Want to Achieve This Month",
    "My Wildest Dreams",
    "What Success Looks Like to Me",
    "Skills I Want to Master",
    "The Perfect Day, Designed",
    "What I'm Working Toward Right Now",
    "Big Goals, Small Steps",
    "Things I Keep Putting Off",
    "Habits I Want to Build",
    "What I Would Do With More Time",
    "Dreams That Scare Me a Little",
    "The Next Big Adventure",
    "What I'm Saving Up For",
    "The Person I Want to Become",
    "Resolutions I Actually Mean This Time",
    "One Thing I Want to Change",
    "The Project I Keep Dreaming About",
    "If I Could Start Over",
    "Goals I Am Quietly Chasing",
    "Ambitions I Haven't Admitted Out Loud",
    "My Vision Board in Words",

    // ── Travel & Places ───────────────────────────────────────
    "Dream Travel Destinations",
    "Places I Want to Visit",
    "Let's Go to Japan",
    "What If I Moved Abroad?",
    "Cities I Want to Live In",
    "My Perfect Road Trip Route",
    "Countries on My List",
    "Things to Do in Paris",
    "Everywhere I've Been",
    "The Trip That Changed Me",
    "Places I Want to Return To",
    "Hidden Gems I've Discovered",
    "The Best Street Food I've Ever Had",
    "Travel Memories I Never Want to Forget",
    "What I Learned From Traveling Alone",
    "The Best Hotel I Ever Stayed In",
    "Adventures I Want to Have",
    "Things to Pack for Any Trip",
    "What I Miss About That Place",
    "Airports, Trains, and Getting Lost",
    "The View That Took My Breath Away",
    "A Weekend in a City I Love",
    "Why Everyone should Travel",
    "Beaches I Want to See",
    "Mountains I Want to Climb",
    "My thoughts on Villages",
    "Travel Lessons Nobody Tells You",
    "The Worst Trip That Became the Best Story",
    "Things to Do Before Leaving a City",
    "My Dream Itinerary",

    // ── Everyday Life & Routines ──────────────────────────────
    "Weekend Plans",
    "The Perfect Morning Routine",
    "My Evening Wind-Down Ritual",
    "How I Spent My Weekend",
    "Daily Journal",
    "Things I Do Every Day Without Thinking",
    "My Ideal Sunday",
    "What a Good Week Looks Like",
    "Things That Make a Day Feel Complete",
    "Morning Pages",
    "Late Night Thoughts",
    "Things I'm Grateful For Today",
    "What I Did Today",
    "The Tiny Rituals I Love",
    "How I Unwind",
    "Productivity Systems That Actually Work for Me",
    "What I Eat in a Day",
    "Things I Do to Feel Human Again",
    "My Current Routine",
    "What I'm Trying to Do Less Of",
    "Simple Joys",
    "Things I Do Just for Myself",
    "How I Spend My Free Time",
    "My Current Morning Playlist",
    "Things That Make Me Feel at Home",
    "Comfort Foods and Where They Come From",
    "The Little Things I Look Forward To",
    "Chores I Actually Don't Mind",
    "A Week of Meals",
    "List of Eating Habits I Want to Quit",
    "Things I Want to Stop Wasting Time On",

    // ── Happiness & Things I Love ─────────────────────────────
    "Things That Make Me Happy",
    "Random Thoughts",
    "Things I Am Obsessed With Right Now",
    "My Current Favorite Things",
    "Things That Make Me Laugh",
    "What Brings Me Joy",
    "Little Things That Made Today Good",
    "My Comfort Shows",
    "Favorite Smells and What They Remind Me Of",
    "Places That Feel Like Home",
    "Things I'm Looking Forward To",
    "What I Love About Winter",
    "What I Love About Summer",
    "Things That Feel Like a Hug",
    "Words That I Love",
    "The Aesthetic I Want My Life to Have",
    "Things I Keep Coming Back To",
    "My Favorite Time of Day",
    "What Makes Me Feel Alive",
    "Hobbies I Keep Returning To",
    "Things Worth Doing Slowly",
    "Underrated Pleasures",
    "My Favorite Kind of Afternoon",
    "Things I Never Get Tired Of",
    "What Comfort Means to Me",
    "Simple Things That Feel Luxurious",
    "My Happy Places",
    "Small Moments I Want to Bottle Up",
    "Reasons Today Was Good",
    "The Feeling I'm Always Chasing",
    "For The Woman I Love The Most",
    "For The Man I Love The Most",
    // ── People & Relationships ────────────────────────────────
    "People Who Changed My Life",
    "Things I Want to Say to the People I Love",
    "What I Look for in a Friend",
    "The Most Interesting Person I've Ever Met",
    "Things I Learned From My Parents",
    "People I Admire and Why",
    "Relationships Worth Nurturing",
    "The Best Conversations I've Had",
    "Things I Want to Tell My Best Friend",
    "What Friendship Looks Like to Me",
    "People I Want to Reconnect With",
    "Things I've Learned From Others",
    "What I Appreciate About the People Around Me",
    "Lessons From Someone I Respect",
    "Qualities I Want in My People",
    "The Community I Want to Build",
    "How to Be a Better Friend",
    "Things I Wish I'd Said",
    "What Love Feels Like",
    "How I Show People I Care",

    // ── Books, Films & Culture ────────────────────────────────
    "Best Movies I Watched",
    "Books I Need to Read",
    "Books That Changed My Mind",
    "Songs On Repeat",
    "Albums That Defined a Year",
    "My All-Time Favorite Films",
    "Shows I Can't Stop Watching",
    "Books I Keep Recommending",
    "Movies That Made Me Cry",
    "Songs That Feel Like a Memory",
    "Podcasts Worth Listening To",
    "Books I Wish I'd Read Sooner",
    "Films That Changed How I See the World",
    "My Desert Island Albums",
    "Artists I've Discovered This Year",
    "Quotes I Keep Coming Back To",
    "Stories That Stuck With Me",
    "What I'm Reading Right Now",
    "Movies I Watch When I Need Comfort",
    "Books That Felt Like They Were Written for Me",
    "The Soundtrack to My Life",
    "Films I Think About All the Time",
    "My Favorite Openings Lines in Books",
    "Things I've Watched More Than Once",
    "What I'm Listening to This Week",
    "Documentaries That Opened My Eyes",
    "Poems I Keep Returning To",
    "Shows I'm Embarrassed I Binged",
    "The Book That Made Me Want to Read More",
    "Music That Takes Me Back",

    // ── Food & Recipes ────────────────────────────────────────
    "My Favorite Recipes",
    "Chai or Coffee?",
    "Dishes I Want to Learn to Cook",
    "The Best Meal I've Ever Had",
    "Comfort Foods",
    "Things I Want to Cook This Month",
    "Restaurants I Need to Try",
    "My Go-To Weeknight Dinners",
    "Foods I Grew Up With",
    "Flavors From My Childhood",
    "The Perfect Breakfast",
    "Baking Projects I Want to Try",
    "Street Food Worth Traveling For",
    "Things I Cook for People I Love",
    "My Pantry Staples",
    "Cuisines I Want to Explore",
    "Meals That Feel Like a Celebration",
    "The Dish I Always Come Back To",
    "Foods That Remind Me of People",
    "What I Eat When No One's Watching",
    "Snacks That Carry Me Through the Day",

    // ── Creativity & Ideas ────────────────────────────────────
    "Ideas Worth Building",
    "Random Ideas I Don't Want to Lose",
    "Projects I Want to Start",
    "Things I Want to Create",
    "Creative Experiments",
    "Ideas That Kept Me Up at Night",
    "Future Business Ideas",
    "Things I Want to Make With My Hands",
    "Side Projects Worth Starting",
    "What I Would Build If I Had Six Months Free",
    "The Idea I Keep Coming Back To",
    "Creative Goals for the Year",
    "Concepts I Find Fascinating",
    "Experiments Worth Running",
    "Things I Want to Try at Least Once",
    "What I Would Do With a Blank Canvas",
    "The Product I Wish Existed",
    "Content I Want to Make",
    "Things I Want to Write About",
    "Creative Blocks and How I Break Them",

    // ── Introspection & Mental Health ─────────────────────────
    "Things That Drain Me",
    "Things That Recharge Me",
    "What Anxiety Feels Like for Me",
    "Things I Do When I Feel Low",
    "What Self-Care Actually Looks Like for Me",
    "Thoughts I Need to Untangle",
    "Things I'm Working on Emotionally",
    "What Peace Feels Like",
    "Things I Need to Let Go Of",
    "Fears I'm Facing",
    "What Overwhelms Me",
    "What Grounds Me",
    "Things I'm Proud Of",
    "Insecurities I'm Working Through",
    "What Makes Me Feel Safe",
    "Things I Need to Hear Sometimes",
    "My Relationship With Rest",
    "What Rest Actually Looks Like",
    "How I Process Difficult Things",
    "Things I'm Learning to Accept",
    "What I Need More Of",
    "What I Need Less Of",
    "Boundaries I'm Getting Better At",
    "The Feelings I Don't Have Words For Yet",
    "What I'm Healing From",
    "Questions I'm Sitting With",
    "Things I'm Grateful For",
    "What Worry Looks Like vs. What Is Real",
    "When I Feel Most Like Myself",
    "What I Owe Myself",
    "Overcoming My Resentful Feelings",

    // ── Nature & The World ────────────────────────────────────
    "Things I Notice on Walks",
    "What Nature Does to My Mind",
    "Seasons and What They Mean to Me",
    "My Favorite Weather",
    "Places in Nature That Feel Sacred",
    "What the Sea Makes Me Think About",
    "Animal Encounters I'll Never Forget",
    "Why I Go Outside",
    "The Best Sunrise I've Seen",
    "What Rain Sounds Like Where I Am",
    "Gardens I Want to Visit",
    "Things Worth Growing",
    "What I Notice in Spring",
    "The Quiet of Winter",
    "Landscapes That Stayed With Me",
    "What Stargazing Feels Like",
    "Things I Want to Do Outdoors",
    "The World As I See It",
    "Why the Earth Is Worth Taking Care Of",
    "What Slowing Down in Nature Taught Me",

    // ── Philosophy & Big Questions ────────────────────────────
    "What I Believe In",
    "What is The Meaning of Life?",
    "Questions Worth Thinking About",
    "Things I Can't Explain But Feel Are True",
    "What Time Does to Everything",
    "What Happiness Really Means",
    "Does Anything Happen for a Reason?",
    "What It Means to Live Well",
    "Things Worth Caring About",
    "What I Would Defend",
    "The Ideas That Changed How I Think",
    "Is Luck Real?",
    "What Fairness Looks Like to Me",
    "What the World Could Be",
    "Things That Can't Be Measured",
    "Why People Are the Way They Are",
    "What I Think About When I Can't Sleep",
    "The Questions I Return to Again and Again",
    "What I Believe About Kindness",
    "The Paradoxes I Live With",
    "What Enough Really Means",

    // ── Health & Wellness ─────────────────────────────────────
    "My Fitness Journey",
    "Things That Make My Body Feel Good",
    "Movement I Actually Enjoy",
    "What Health Means to Me",
    "How Sleep Changed My Life",
    "Things I Do to Feel Energized",
    "My Relationship With Exercise",
    "Foods That Make Me Feel Good",
    "What My Body Is Telling Me",
    "Things I'm Doing for My Future Self",
    "How I've Changed Physically Over the Years",
    "What I Wish I'd Known About Health",
    "Rest as a Practice",
    "Mental Health Days and What I Do on Them",
    "Things Worth Protecting About My Health",
    "Workouts I Actually Want to Do",
    "What Strong Means to Me",
    "How I Stay Balanced",
    "Things My Body Does That Amaze Me",
    "What Taking Care of Myself Looks Like This Year",

    // ── Work & Purpose ────────────────────────────────────────
    "What Work Means to Me",
    "The Career I Want to Have",
    "Things I Want from a Job",
    "What I'm Learning at Work",
    "How I Want to Spend My Workdays",
    "What Motivates Me",
    "Problems I Want to Solve",
    "What I Would Do If I Weren't Afraid",
    "The Kind of Work That Doesn't Feel Like Work",
    "Things I've Built That I'm Proud Of",
    "How to Find Work That Matters",
    "What I Bring to the Table",
    "Collaboration vs. Working Alone",
    "The Legacy I Want to Leave",
    "Things Work Has Taught Me About People",
    "How I Want to Be Remembered Professionally",
    "Skills I've Picked Up Along the Way",
    "What Leadership Means to Me",
    "The Best Professional Advice I've Received",
    "Things I No Longer Tolerate at Work",

    // ── Miscellaneous & Fun ───────────────────────────────────
    "Things I Find Funny",
    "The Strangest Thing That Happened to Me",
    "Conspiracy Theories I Half Believe",
    "Things I Do That Make No Sense",
    "If I Had a TV Show",
    "My Ideal Dinner Party Guest List",
    "Things I Think About in the Shower",
    "The Best Compliment I Ever Received",
    "Things I'm Weirdly Good At",
    "Things I Thought Were True That Weren't",
    "If I Could Have Any Superpower",
    "Pet Peeves I Can't Let Go Of",
    "The Funniest Thing That Happened This Week",
    "Things Everyone Should Try Once",
    "Rules I Live By That I Never Stated Out Loud",
    "What I Would Order at Any Restaurant",
    "Things That Are Overrated and Underrated",
    "If I Could Live in Any Era",
    "What I Would Do on a Day With No Obligations",
    "The Most Random Fact I Know",
    "Things I've Learned From Children",
    "What I Would Tell an Alien About Earth",
    "Things I'm Embarrassed I Didn't Know Earlier",
    "Questions I Would Ask Anyone",
    "Inventions I Wish Existed",
    "Things Everyone Experiences but Nobody Talks About",
    "What I Would Change About the World",
    "Games I Could Play Forever",
    "Things That Feel Different Than They Did Five Years Ago",
    "What I Believe About Luck",

    // ── Seasons of Life ───────────────────────────────────────
    "What This Season of Life Is Teaching Me",
    "Growing Pains Worth Having",
    "The Phase I'm In Right Now",
    "What I Thought Adulthood Would Be",
    "Things Nobody Warned Me About",
    "What Getting Older Actually Feels Like",
    "The Decade That Shaped Me Most",
    "What I Wanted at Twenty vs. Now",
    "How My Priorities Have Shifted",
    "The Stages of Becoming Yourself",
    "Things I Outgrew and Things I Grew Into",
    "What I Would Tell Myself at Fifteen",
    "Looking Back at Last Year",
    "The Year Everything Changed",
    "What I'm Leaving Behind",
    "What I'm Carrying Forward",
    "The Season I'm Entering",
    "What Growing Up in My Family Taught Me",
    "How I've Surprised Myself",
    "The Life I Didn't Expect to Have",

    // ── Community & The World ─────────────────────────────────
    "Things Worth Fighting For",
    "What a Better World Looks Like to Me",
    "Problems That Keep Me Up at Night",
    "Things People Are Getting Right",
    "How I Want to Contribute",
    "Small Ways to Make Things Better",
    "What Community Means to Me",
    "Things That Give Me Hope",
    "Issues That Matter to Me",
    "What I Wish More People Talked About",
    "Causes Worth Supporting",
    "Things I Think We Got Wrong",
    "What the Next Generation Needs",
    "What I Want to Leave the World",
    "Things That Bring People Together",
    "What Kindness Looks Like in Practice",
    "The Role I Want to Play in My Community",
    "Traditions Worth Keeping",
    "Things That Make Society Better",
    "What I Believe About Progress",

    // ── Curiosity & Learning ──────────────────────────────────
    "Things I Recently Learned",
    "Topics I Want to Go Deep On",
    "Ideas That Fascinate Me Right Now",
    "What I Wish School Had Taught Me",
    "Things I Keep Researching",
    "Questions Science Hasn't Answered Yet",
    "Things That Made Me Think Differently",
    "Rabbit Holes I've Fallen Into",
    "Things I'm Curious About",
    "What Learning Looks Like for Me",
    "Skills Worth Having That Nobody Teaches",
    "Things That Made Me Smarter",
    "Experiments in My Own Life",
    "Lessons From Unexpected Places",
    "Books That Rewired My Brain",
    "Things I Thought I Knew",
    "What I Want to Understand Better",
    "The Subject I Wish I'd Studied",
    "Things I'm Teaching Myself",
    "Why I Never Want to Stop Learning",

    // ── Stories & Writing ─────────────────────────────────────
    "That Time When I Got Injured and Hid it From My Parents",
    "Stories of Me Being Bullied",
    "The Story Behind My Name",
    "A Childhood Memory in Detail",
    "The Funniest Thing That Ever Happened to Me",
    "A Moment I Replay Often",
    "The Story of How We Met",
    "A Day That Started Badly and Ended Well",
    "The Trip That Didn't Go to Plan",
    "A Mistake That Taught Me Something",
    "The Moment I Knew",
    "Things I Would Put in a Time Capsule",
    "A Day I Would Choose to Live Again",
    "The Best Surprise I Ever Had",
    "Something That Made Me Proud",
    "A Fear I Faced",
    "The Conversation That Changed Something",
    "An Ordinary Day Worth Documenting",
    "What I Saw on My Walk Today",
    "The Last Time I Felt Completely Present",
    "A Story Worth Telling",
    "Something I Witnessed That I'll Never Forget",
    "What Will I Do If I Get A Time Machine",
    "Who Is The One Person I Badly Want To Punch In The Face?",

    // ── Home & Space ──────────────────────────────────────────
    "What My Ideal Home Looks Like",
    "Spaces That Inspire Me",
    "How I've Made a Place Feel Like Mine",
    "Things I Want in My Home One Day",
    "What My Bedroom Says About Me",
    "The Neighborhoods I've Loved",
    "What Makes a House a Home",
    "Things I Would Change About Where I Live",
    "My Dream Kitchen",
    "Places I've Called Home",
    "What I Want My Space to Feel Like",
    "The Street I Grew Up On",
    "How I Create a Space to Think",
    "Things I've Collected Over the Years",
    "My Relationship With Decluttering",
    "What Cozy Means to Me",
    "The Room I Spend the Most Time In",
    "Things That Make a Space Feel Safe",
    "My Dream Garden",
    "Designing the Life I Want to Live In",
    "Thoughts About Where I Am Sitting Right Now",

    // ── The Last Ten ──────────────────────────────────────────
    "What I Notice That Others Miss",
    "What Others Notice That I Miss",
    "Sounds That Take Me Somewhere Else",
    "The Colour That Describes My Mood Right Now",
    "Things I Would Do on the Perfect Saturday",
    "What I Would Pack for a Month Away",
    "The Meal I Would Request for My Birthday",
    "Habits Stolen From People I Admire",
    "What a Good Conversation Feels Like",
    "Things I Want to Do While I Still Can",
    "Everything I'm Looking Forward To",
];



export const generateTitle = () => {
    return defaultTitles[Math.floor(Math.random() * defaultTitles.length)];
};